{% set name = "testcontainers" %}
{% set version = "4.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/testcontainers-{{ version }}.tar.gz
  sha256: 348c72d369d0bd52b57ab4f07a965ae9562837098c28f0522b969b064b779f10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - docker-py
    - urllib3
    - wrapt
    - typing-extensions
    - python-dotenv

test:
  imports:
    - testcontainers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/testcontainers/testcontainers-python
  summary: Python library for throwaway instances of anything that can run in a Docker container
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - YYYasin19
