{% set name = "testcontainers" %}
{% set version = "4.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/testcontainers-{{ version }}.tar.gz
  sha256: 2cd6af070109ff68c1ab5389dc89c86c2dc3ab30a21ca734b2cb8f0f80ad479e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0
    - docker-py
    - urllib3
    - wrapt
    - typing-extensions
    - python-dotenv

test:
  imports:
    - testcontainers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/testcontainers/testcontainers-python
  summary: Python library for throwaway instances of anything that can run in a Docker container
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - YYYasin19
